#!/bin/bash

MAC2EUI64=/usr/bin/mac2eui64

source /etc/default/nfdhcpd

FULLHOST=$(hostname -f)

FIRST=0
LAST=$((GANETI_INSTANCE_NIC_COUNT - 1))
for idx in $(seq $FIRST $LAST); do
  link=GANETI_INSTANCE_NIC${idx}_LINK
  eval LINK=\$$link
  uplink=$(ip -6 route list table $LINK | grep "default via" | awk '{print $5}')
  mac=GANETI_INSTANCE_NIC${idx}_MAC
  eval MAC=\$$mac
  subnet6=GANETI_INSTANCE_NIC${idx}_NETWORK_SUBNET6
  eval SUBNET6=\$$subnet6
  if [ "x$SUBNET6" == "x" ]; then
      SUBNET6=$(ip -6 route list table $LINK | awk '/\/64/ {print $1; exit}')
  fi

  EUI64=$($MAC2EUI64 $MAC $SUBNET6 2>/dev/null)

  # if the first nic is bridged, don't do anything about ARP/ND
  mode=GANETI_INSTANCE_NIC${idx}_MODE
  eval MODE=\$$mode
  if [ "$MODE" != "bridged" ]; then
    tags=GANETI_INSTANCE_NIC${idx}_NETWORK_TAGS
    eval TAGS=\$$tags
    if [ "x$TAGS" == "x" ]; then
        TAGS='ip-less-routed'
    fi

    if [ "$GANETI_INSTANCE_PRIMARY" == "$FULLHOST" ]; then
      for tag in $TAGS; do
        case $tag in
        $IP_LESS_ROUTED_TAG)

          hooks-log clear-proxy-ndp "ip -6 neigh del proxy $EUI64 dev $uplink"
          ip -6 neigh del proxy $EUI64 dev $uplink >/dev/null 2>&1
        ;;
        esac
      done
    elif [ "$GANETI_NEW_PRIMARY" == "$FULLHOST" ]; then
      for tag in $TAGS; do
        case $tag in
        $IP_LESS_ROUTED_TAG)
          ip=GANETI_INSTANCE_NIC${idx}_IP
          eval IP=\$$ip
          # Send GARP from host to upstream router to speed up mac change for the VMs IP
          hooks-log clear-proxy-ndp "arping -c 8 -A -I $uplink $IP"
          echo 1 > /proc/sys/net/ipv4/ip_nonlocal_bind
          arping -c 8 -A -I $uplink $IP
          echo 0 > /proc/sys/net/ipv4/ip_nonlocal_bind
          # Send Unsolicited Neighbor Advertisement to speed up nd change for the VMs IP
          hooks-log clear-proxy-ndp "ndsend $EUI64 $uplink"
          ndsend $EUI64 $uplink
          ;;
        esac
      done
    fi
  fi
done

exit 0
